name: 'Packages Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'base'
            split_repository: 'google.base'
          - local_path: 'calendar'
            split_repository: 'google.calendar'
          - local_path: 'drive'
            split_repository: 'google.drive'

    steps:
      - uses: actions/checkout@v2
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.1'
        with:
          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'battis'
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.1'
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: 'packages/${{ matrix.package.local_path }}'

          repository_organization: 'battis'
